const $=s=>document.querySelector(s);let state={name:'',mode:'',questions:[],index:0,answers:[],left:1200,timer:null};
const labels={html:'HTML5',css:'CSS3',bootstrap:'Bootstrap 5',computer:'Kompyuter savodxonligi',all:'Aralash test'};
function getQuestions(mode){let q=QUESTIONS.map((x,i)=>({...x,id:i+1,opts:[...x[2]],answer:x[3]}));if(mode==='all')return q.sort(()=>Math.random()-.5);const key=labels[mode];return q.filter(x=>x[0]===key.replace('HTML5','HTML').replace('CSS3','CSS').replace('Bootstrap 5','Bootstrap')).sort(()=>Math.random()-.5)}
function start(mode){const f=$('#firstName').value.trim(),l=$('#lastName').value.trim();if(!f||!l){$('#firstName').focus();alert('Avval ism va familiyangizni kiriting.');return}const qs=getQuestions(mode);state={name:`${f} ${l}`,mode,questions:qs,index:0,answers:Array(qs.length).fill(null),left:Math.max(600,qs.length*24),timer:null};$('#start').classList.add('hidden');$('#quiz').classList.remove('hidden');state.timer=setInterval(tick,1000);render()}
function tick(){state.left--;if(state.left<=0){finish();return}const m=String(Math.floor(state.left/60)).padStart(2,'0'),s=String(state.left%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`;if(state.left<60)$('#timer').style.color='var(--danger)'}
function render(){const q=state.questions[state.index];$('#categoryLabel').textContent=`${labels[state.mode]} • SAVOL ${state.index+1}`;$('#questionText').textContent=q[1];$('#counter').textContent=`${state.index+1} / ${state.questions.length}`;$('#progressBar').style.width=`${((state.index+1)/state.questions.length)*100}%`;let c=state.answers.filter((a,i)=>a===state.questions[i]?.answer).length;$('#scoreLive').textContent=`${c} to‘g‘ri`;$('#answers').innerHTML=q[2].map((a,i)=>`<button class="answer ${state.answers[state.index]===i?'selected':''}" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${a}</span></button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{state.answers[state.index]=+b.dataset.i;render()});$('#prev').disabled=state.index===0;$('#next').textContent=state.index===state.questions.length-1?'Yakunlash →':'Keyingi →'}
$('#next').onclick=()=>state.index===state.questions.length-1?finish():(state.index++,render());$('#prev').onclick=()=>{if(state.index){state.index--;render()}};
function finish(){clearInterval(state.timer);let correct=state.answers.reduce((n,a,i)=>n+(a===state.questions[i].answer?1:0),0),total=state.questions.length,wrong=total-correct,pct=Math.round(correct/total*100);$('#quiz').classList.add('hidden');$('#result').classList.remove('hidden');$('#resultName').textContent=state.name;$('#resultScore').textContent=pct+'%';$('#total').textContent=total;$('#correct').textContent=correct;$('#wrong').textContent=wrong;sendResult({name:state.name,mode:labels[state.mode],total,correct,wrong,pct,answers:state.questions.map((q,i)=>({question:q[1],selected:q[2][state.answers[i]]||'Javob berilmagan',correct:q[2][q.answer]}))})}
async function sendResult(data){const el=$('#sendStatus');try{const API_URL=(window.IT_QUIZ_API_URL||'/api/result');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw 0;el.textContent='✓ Natija Telegram botga yuborildi';el.style.color='var(--accent)'}catch(e){el.textContent='⚠ Natija serverga yuborilmadi. Server/API sozlamalarini tekshiring.'}}
$('#details').onclick=()=>{$('#review').classList.toggle('hidden');if(!$('#review').classList.contains('hidden')){$('#review').innerHTML=state.questions.map((q,i)=>{const ok=state.answers[i]===q.answer;return `<div class="review-item ${ok?'ok':'bad'}"><b>${i+1}. ${q[1]}</b><br><small>Sizning javob: ${q[2][state.answers[i]]||'Javob berilmagan'}<br>To‘g‘ri javob: ${q[2][q.answer]}</small></div>`}).join('')}};$('#restart').onclick=()=>location.reload();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));
