const QUESTIONS = [
/* HTML 1-50 */
['HTML','HTML hujjatining asosiy ildiz elementi qaysi?',['<html>','<body>','<head>','<main>'],0],
['HTML','Brauzer oynasida ko‘rinadigan asosiy kontent qaysi element ichida bo‘ladi?',['<head>','<body>','<meta>','<title>'],1],
['HTML','Sahifa nomini brauzer tabida beruvchi teg qaysi?',['<name>','<header>','<title>','<caption>'],2],
['HTML','Eng katta sarlavha tegi qaysi?',['<h6>','<head>','<h1>','<header>'],2],
['HTML','Paragraf yaratish uchun qaysi teg ishlatiladi?',['<p>','<para>','<text>','<pg>'],0],
['HTML','Havola yaratish uchun qaysi teg ishlatiladi?',['<link>','<a>','<href>','<url>'],1],
['HTML','Rasm manzilini ko‘rsatadigan atribut qaysi?',['href','src','alt','path'],1],
['HTML','Rasm yuklanmasa alternativ matn qaysi atributda yoziladi?',['title','alt','text','fallback'],1],
['HTML','Tartibli ro‘yxat tegi qaysi?',['<ul>','<li>','<ol>','<list>'],2],
['HTML','Ro‘yxat elementi qaysi teg bilan yoziladi?',['<item>','<li>','<list>','<el>'],1],
['HTML','Forma yaratish tegi qaysi?',['<input>','<form>','<fieldset>','<data>'],1],
['HTML','Bir qatorli matn kiritish uchun input type qaysi?',['text','string','line','input'],0],
['HTML','Parol maydoni uchun input type qaysi?',['secret','password','hidden','pass'],1],
['HTML','Email kiritish uchun mos input type qaysi?',['mail','email','text-email','address'],1],
['HTML','Tugma yaratishning semantik usuli qaysi?',['<click>','<button>','<btn>','<action>'],1],
['HTML','HTML5 semantik navigatsiya elementi qaysi?',['<nav>','<navigate>','<menu-bar>','<links>'],0],
['HTML','Mustaqil maqola mazmuni uchun qaysi semantik teg mos?',['<article>','<content>','<post>','<story>'],0],
['HTML','Sahifaning kirish qismi uchun qaysi teg ishlatiladi?',['<top>','<header>','<intro>','<head>'],1],
['HTML','Pastki qism uchun semantik teg qaysi?',['<bottom>','<footer>','<end>','<aside>'],1],
['HTML','Yon panel mazmuni uchun qaysi teg mos?',['<side>','<aside>','<panel>','<extra>'],1],
['HTML','HTML kommentariyasi qaysi ko‘rinishda yoziladi?',['// comment','/* comment */','<!-- comment -->','# comment'],2],
['HTML','Boshqa sahifani joriy sahifaga joylash uchun qaysi element ishlatiladi?',['<frame>','<iframe>','<embed-page>','<window>'],1],
['HTML','Video joylash uchun HTML5 tegi qaysi?',['<movie>','<media>','<video>','<film>'],2],
['HTML','Audio joylash uchun qaysi tegi ishlatiladi?',['<sound>','<audio>','<music>','<voice>'],1],
['HTML','HTML faylining deklaratsiyasi odatda nima bilan boshlanadi?',['<!DOCTYPE html>','<html5>','<!HTML>','<doctype>'],0],
['HTML','Meta charset UTF-8 nima uchun?',['Rasm yuklash','Kodlashni belgilash','CSS ulash','Forma yuborish'],1],
['HTML','CSS faylini ulash uchun qaysi teg ishlatiladi?',['<css>','<style src>','<link>','<script>'],2],
['HTML','JavaScript faylini ulash uchun qaysi teg?',['<js>','<script>','<javascript>','<code>'],1],
['HTML','CSS ulashda qaysi atribut fayl manzilini bildiradi?',['src','href','link','url'],1],
['HTML','HTMLda yangi qatordan o‘tish uchun qaysi teg?',['<newline>','<br>','<lb>','<break>'],1],
['HTML','Gorizontal chiziq chiqaruvchi teg qaysi?',['<line>','<hr>','<border>','<rule>'],1],
['HTML','Formadagi maydon nomini bog‘lash uchun qaysi teg ishlatiladi?',['<label>','<name>','<caption>','<field>'],0],
['HTML','Checkbox uchun input type qaysi?',['check','checkbox','tick','select'],1],
['HTML','Radio tugmalar uchun input type qaysi?',['radio','choice','option','select-one'],0],
['HTML','Fayl tanlash uchun input type qaysi?',['upload','file','document','attachment'],1],
['HTML','Faqat bitta qiymat tanlashga mos element qaysi?',['<textarea>','<select>','<input type="text">','<output>'],1],
['HTML','Ko‘p qatorli matn maydoni qaysi?',['<multiline>','<textarea>','<textblock>','<input-area>'],1],
['HTML','Elementga noyob identifikator beruvchi atribut qaysi?',['class','id','name','key'],1],
['HTML','Bir nechta elementga umumiy uslub berishda ko‘p ishlatiladigan atribut qaysi?',['id','class','style-id','group'],1],
['HTML','Elementni yangi tabda ochish uchun anchor target qiymati qaysi?',['_self','_blank','_newtab','_topnew'],1],
['HTML','Tashqi manba bilan bog‘liq metadata uchun qaysi teg ishlatiladi?',['<meta>','<data>','<info>','<headinfo>'],0],
['HTML','HTML jadvalining qator tegi qaysi?',['<td>','<row>','<tr>','<line>'],2],
['HTML','Jadval katagi tegi qaysi?',['<cell>','<td>','<tc>','<data>'],1],
['HTML','Jadval sarlavha katagi qaysi?',['<th>','<thead-cell>','<header-cell>','<caption-cell>'],0],
['HTML','Jadval sarlavha qismi uchun qaysi teg?',['<top>','<thead>','<header>','<thgroup>'],1],
['HTML','Jadval tanasi uchun qaysi teg?',['<tbody>','<bodytable>','<mainbody>','<rows>'],0],
['HTML','Jadval pastki qismi uchun qaysi teg?',['<bottom>','<tfoot>','<footer>','<end>'],1],
['HTML','Elementni yashirish uchun global boolean atribut qaysi?',['hidden','invisible','display','hide'],0],
['HTML','Input maydonini majburiy qilish uchun qaysi atribut?',['must','required','validate','needed'],1],
['HTML','HTML5da tez-tez ishlatiladigan responsive rasm uchun qaysi atribut muhim?',['alt','srcset','target','poster'],1],
/* CSS 51-100 */
['CSS','CSS nimani boshqaradi?',['Sahifa tuzilmasi','Ko‘rinish va uslub','Ma’lumotlar bazasi','Server'],1],
['CSS','CSS selektori .box nimani tanlaydi?',['id box','class box','tag box','name box'],1],
['CSS','#header selektori nimani tanlaydi?',['class','id','tag','attribute'],1],
['CSS','Element nomi bilan yozilgan selector nima?',['Universal','Class','Type selector','Pseudo'],2],
['CSS','Universal selector qaysi?',['#','.', '*','@'],2],
['CSS','CSS faylini HTMLga ulashning to‘g‘ri usuli?',['<css href="a.css">','<link rel="stylesheet" href="a.css">','<style src="a.css">','<script src="a.css">'],1],
['CSS','Matn rangini o‘zgartiruvchi property?',['font-color','color','text-color','foreground'],1],
['CSS','Fon rangini o‘zgartiruvchi property?',['background-color','bg','color-bg','fill'],0],
['CSS','Shrift o‘lchami propertysi?',['text-size','font-size','size','font-scale'],1],
['CSS','Qalin shrift uchun property?',['font-style','font-weight','text-bold','weight-font'],1],
['CSS','Italic ko‘rinish uchun property?',['font-style','font-weight','text-style','italicize'],0],
['CSS','Matnni markazga tekislash propertysi?',['align','text-align','text-center','font-align'],1],
['CSS','Elementning tashqi bo‘shlig‘i?',['padding','margin','gap','space'],1],
['CSS','Elementning ichki bo‘shlig‘i?',['padding','margin','inside','inset'],0],
['CSS','Element borderini beruvchi property?',['outline-box','border','edge','stroke'],1],
['CSS','Burchaklarni yumaloqlash propertysi?',['corner-radius','border-radius','radius','round'],1],
['CSS','Element kengligi qaysi property?',['width','size-x','w','element-width'],0],
['CSS','Element balandligi qaysi property?',['height','size-y','h','element-height'],0],
['CSS','display:flex nima qiladi?',['Grid yaratadi','Flex konteyner qiladi','Elementni yashiradi','Rasm yuklaydi'],1],
['CSS','Flex yo‘nalishini o‘zgartirish propertysi?',['flex-direction','direction-flex','flow','flex-axis'],0],
['CSS','Flex elementlarini asosiy o‘q bo‘yicha joylash?',['align-items','justify-content','place-items','main-align'],1],
['CSS','Flex elementlarini kesishuvchi o‘q bo‘yicha joylash?',['justify-content','align-items','cross-content','items-align'],1],
['CSS','CSS Grid konteynerini yaratish?',['display:grid','grid:on','layout:grid','display:table'],0],
['CSS','position:fixed elementi nimaga nisbatan joylashadi?',['Oddiy oqim','Viewport','Faqat parent','Grid'],1],
['CSS','position:absolute odatda nimaga nisbatan joylashadi?',['Eng yaqin positioned ancestor','Faqat viewport','Body har doim','Flex container'],0],
['CSS','z-index nimani boshqaradi?',['Rang','Qatlam tartibi','Kenglik','Animatsiya tezligi'],1],
['CSS','overflow:hidden nima qiladi?',['Elementni aylantiradi','Tashqariga chiqqan qismini yashiradi','Rangni o‘chiradi','Paddingni olib tashlaydi'],1],
['CSS','opacity:0 nimani anglatadi?',['Element o‘chadi','Element shaffof bo‘ladi','Element yo‘q qilinadi','Faqat fon shaffof'],1],
['CSS','transition nima uchun?',['Sahifa tarjimasi','Property o‘zgarishini silliqlashtirish','Grid yaratish','Shrift ulash'],1],
['CSS','transform:scale() nima qiladi?',['Buradi','Masshtablaydi','Yashiradi','Rangni o‘zgartiradi'],1],
['CSS','transform:rotate() nima qiladi?',['Siljitadi','Buradi','Kattalashtiradi','Kesadi'],1],
['CSS','Pseudo-class misoli qaysi?',['::before',':hover','.hover','#hover'],1],
['CSS','Pseudo-element misoli qaysi?',[':hover','::before','.before','#before'],1],
['CSS','@media nima uchun?',['Font yuklash','Responsive shartlar','JS yozish','Rasm optimizatsiyasi'],1],
['CSS','box-sizing:border-box nima qiladi?',['Borderni o‘chiradi','Width ichiga padding va borderni hisoblaydi','Marginni nol qiladi','Flex qiladi'],1],
['CSS','CSS o‘zgaruvchisi odatda qanday boshlanadi?',['$','--','@','var-'],1],
['CSS','O‘zgaruvchini ishlatish funksiyasi?',['use()','var()','css()','get()'],1],
['CSS','!important nima qiladi?',['Propertyni o‘chiradi','Uslub ustuvorligini kuchaytiradi','Animatsiya qiladi','Selectorni bekor qiladi'],1],
['CSS','display:none nimani anglatadi?',['Shaffof','Layoutdan olib tashlaydi','Faqat yashiradi, joyi qoladi','Rangni o‘chiradi'],1],
['CSS','visibility:hidden farqi nimada?',['Joy saqlanadi','Layoutdan olib tashlanadi','Faqat width o‘chadi','Hech farqi yo‘q'],0],
['CSS','line-height nimani boshqaradi?',['Harflar kengligi','Qator balandligi','Border','Element balandligi'],1],
['CSS','letter-spacing nimani boshqaradi?',['So‘zlar oralig‘i','Belgilar oralig‘i','Qator balandligi','Margin'],1],
['CSS','text-decoration:underline nima qiladi?',['Qalin qiladi','Tagiga chiziq beradi','Katta qiladi','Italic qiladi'],1],
['CSS','font-family nimani belgilaydi?',['Rang','Shrift oilasi','O‘lcham','Qator balandligi'],1],
['CSS','max-width nima uchun?',['Minimum kenglik','Maksimal kenglik','Balandlik','Padding'],1],
['CSS','min-height nima qiladi?',['Minimal balandlikni belgilaydi','Maksimal balandlik','Kenglik','Margin'],0],
['CSS','gap propertysi asosan qayerda ishlatiladi?',['Flex/Grid elementlari orasida','Faqat body','Faqat input','Fontda'],0],
['CSS','cursor:pointer nima beradi?',['Pointer kursor','Animatsiya','Rang','Click funksiyasi'],0],
['CSS','object-fit:cover odatda nimaga yordam beradi?',['Rasm/video konteynerga sig‘ishiga','Matnni qalinlash','Flex','Border'],0],
['CSS','flex-wrap:wrap nima qiladi?',['Flex elementlarini keyingi qatorga o‘tkazishga ruxsat beradi','Elementni yashiradi','Gridga aylantiradi','Fontni o‘zgartiradi'],0],
/* Bootstrap 101-150 */
['Bootstrap','Bootstrap nima?',['Backend til','CSS framework','Database','OS'],1],
['Bootstrap','Bootstrap 5 grid tizimi nechta ustunga asoslanadi?',['10','12','16','24'],1],
['Bootstrap','Konteyner uchun asosiy class qaysi?',['.box','.container','.wrapper','.bootstrap-container'],1],
['Bootstrap','To‘liq kenglikdagi responsive container class?',['container-fluid','container-full','.fluid','.w-container'],0],
['Bootstrap','Qator yaratish classi?',['.line','.row','.grid-row','.r'],1],
['Bootstrap','Ustun yaratishning umumiy classi?',['.column','.col','.grid','.cell'],1],
['Bootstrap','col-md-6 nimani anglatadi?',['6px margin','md va undan yuqorida 6/12 ustun','6 qator','6% width har doim'],1],
['Bootstrap','Bootstrapda primary tugma classi?',['btn-main','btn btn-primary','button-primary','primary-btn'],1],
['Bootstrap','Bootstrapda success rangi uchun?',['btn btn-success','success-button','btn-green','button-ok'],0],
['Bootstrap','Navbar uchun asosiy class?',['navbar','.navmenu','.navigation','menu-bar'],0],
['Bootstrap','Kartochka komponenti?',['card','box','panel','tile'],0],
['Bootstrap','Card body classi?',['card-content','card-body','body-card','card-inside'],1],
['Bootstrap','Bootstrapda matnni markazlash classi?',['text-center','center-text','align-text','text-middle'],0],
['Bootstrap','Bold matn uchun utility?',['font-bold','fw-bold','bold','text-bold'],1],
['Bootstrap','Responsive rasm uchun class?',['img-responsive','img-fluid','responsive-img','image-fluid'],1],
['Bootstrap','Margin-top 3 utilitysi?',['mt-3','m-top-3','margin-t3','top-margin-3'],0],
['Bootstrap','Padding 4 utilitysi?',['pd-4','p-4','pad-4','padding-4'],1],
['Bootstrap','Display flex utilitysi?',['d-flex','flex','display-flex','df'],0],
['Bootstrap','Flexni markazga joylash uchun ko‘pincha?',['justify-content-center va align-items-center','center-flex','mx-auto only','text-center'],0],
['Bootstrap','Bootstrap breakpoint md odatda qaysi min-widthdan boshlanadi?',['576px','768px','992px','1200px'],1],
['Bootstrap','sm breakpoint?',['576px','768px','992px','1200px'],0],
['Bootstrap','lg breakpoint?',['768px','992px','1200px','1400px'],1],
['Bootstrap','xl breakpoint?',['992px','1200px','1400px','1600px'],1],
['Bootstrap','xxl breakpoint?',['1200px','1400px','1600px','1800px'],1],
['Bootstrap','Bootstrapda alert komponenti?',['alert','notice','message','warning-box'],0],
['Bootstrap','Modal ochish uchun ishlatiladigan data atributlaridan biri?',['data-bs-toggle="modal"','data-toggle-modal','bs-modal','modal-open'],0],
['Bootstrap','Collapse komponenti uchun data-bs-toggle qiymati?',['hide','collapse','accordion','slide'],1],
['Bootstrap','Dropdown ochish uchun?',['data-bs-toggle="dropdown"','data-dropdown="open"','dropdown-toggle-js','bs-dropdown-open'],0],
['Bootstrap','Bootstrap 5 JavaScript odatda nimaga muhtoj?',['jQuery majburiy','jQuery majburiy emas','PHP','React'],1],
['Bootstrap','Badge komponenti uchun class?',['badge','label','tag','pill-badge'],0],
['Bootstrap','Rounded burchak utility?',['rounded','radius','border-round','round-all'],0],
['Bootstrap','Border utility misoli?',['border','bd','outline','stroke'],0],
['Bootstrap','Shadow utility misoli?',['shadow','box-shadow','bs-shadow','elevation'],0],
['Bootstrap','Width 100% utility?',['w-100','width-full','w-full','width-100'],0],
['Bootstrap','Height 100% utility?',['h-100','height-full','h-full','height-100'],0],
['Bootstrap','Elementni markazlashda mx-auto nimaga ta’sir qiladi?',['Gorizontal margin','Vertical margin','Padding','Width'],0],
['Bootstrap','Visually hidden class qaysi?',['visually-hidden','hidden-visually','sr-only-v5','screen-hidden'],0],
['Bootstrap','Bootstrap iconlar frameworkning o‘zida avtomatik keladimi?',['Ha, har doim','Yo‘q, Bootstrap Icons alohida kutubxona','Faqat JS bilan','Faqat CDN bo‘lmasa'],1],
['Bootstrap','Accordion komponenti nima qiladi?',['Ochilib-yopiladigan kontent','Rasm siqadi','Grid yaratadi','Forma yuboradi'],0],
['Bootstrap','Progress bar uchun asosiy class?',['progress','progressbar','bar','loading'],0],
['Bootstrap','Spinner uchun class?',['spinner-border','loader','spin','loading-spinner'],0],
['Bootstrap','Toast nima?',['Kichik vaqtinchalik bildirishnoma','Jadval','Navbar','Modal oynaning turi'],0],
['Bootstrap','Bootstrapda list-group classi nima uchun?',['Ro‘yxat komponenti','Grid','Form','Modal'],0],
['Bootstrap','Table uchun responsive wrapper?',['table-responsive','responsive-table','table-fluid','overflow-table'],0],
['Bootstrap','Form control input classi?',['form-control','input-control','control-form','form-input'],0],
['Bootstrap','Form check checkbox uchun?',['form-check','check-form','checkbox','form-box'],0],
['Bootstrap','Bootstrap gridda offset-2 nimani anglatadi?',['2 ustun joy tashlaydi','2px margin','2 qator','2% padding'],0],
['Bootstrap','Bootstrap utility classlarining afzalligi?',['Tezkor uslublash','Database yaratish','Server ishlatish','HTMLni kompilyatsiya qilish'],0],
['Bootstrap','Bootstrapda responsive breakpointlar media queryga asoslanadimi?',['Ha','Yo‘q','Faqat JS','Faqat CSS variables'],0],
/* Computer 151-200 */
['Kompyuter','CPU nimani anglatadi?',['Central Processing Unit','Computer Power Utility','Core Program Unit','Central Program User'],0],
['Kompyuter','RAM qanday xotira?',['Doimiy','Tezkor vaqtinchalik','Faqat tashqi','Faqat grafik'],1],
['Kompyuter','SSD va HDDning asosiy farqi?',['SSD mexanik disk','SSD odatda flash xotiradan foydalanadi','HDD RAM','Farqi yo‘q'],1],
['Kompyuter','Operatsion tizimga misol?',['Windows','HTML','HTTP','CSS'],0],
['Kompyuter','Windowsda faylni nusxalash shortcut?',['Ctrl+X','Ctrl+C','Ctrl+V','Ctrl+Z'],1],
['Kompyuter','Joylashtirish shortcut?',['Ctrl+P','Ctrl+V','Ctrl+S','Ctrl+F'],1],
['Kompyuter','Saqlash shortcut?',['Ctrl+S','Ctrl+D','Ctrl+W','Ctrl+R'],0],
['Kompyuter','Qidirish shortcut?',['Ctrl+F','Ctrl+G','Ctrl+Q','Ctrl+E'],0],
['Kompyuter','Faylni qayta nomlash Windowsda odatda?',['F2','F4','F8','F12'],0],
['Kompyuter','Task Manager ochishning mashhur shortcutlaridan biri?',['Ctrl+Shift+Esc','Ctrl+Alt+S','Alt+F2','Win+T'],0],
['Kompyuter','Brauzer nima?',['Internet sahifalarini ko‘rsatuvchi dastur','Antivirus','OS','Printer drayveri'],0],
['Kompyuter','Google Chrome nima?',['Brauzer','OS','Database','Compiler'],0],
['Kompyuter','URL nimani bildiradi?',['Uniform Resource Locator','User Router Link','Universal RAM Location','Unified Remote Login'],0],
['Kompyuter','HTTP nima?',['Web aloqa protokoli','Video format','CPU turi','Fayl kengaytmasi'],0],
['Kompyuter','HTTPSdagi S nimani anglatadi?',['Secure','Server','System','Simple'],0],
['Kompyuter','IP address nima uchun?',['Tarmoqdagi qurilmani aniqlash/manzillash','Rasm siqish','Audio yozish','Fayl o‘chirish'],0],
['Kompyuter','Wi‑Fi nima?',['Simsiz tarmoq texnologiyasi','Antivirus','Fayl formati','Monitor turi'],0],
['Kompyuter','LAN nima?',['Local Area Network','Large Access Node','Local App Name','Link Area Number'],0],
['Kompyuter','USB nimaga ishlatiladi?',['Qurilmalarni ulash va ma’lumot uzatish','Faqat internet','Faqat monitor','Faqat audio'],0],
['Kompyuter','HDMI asosan nima uchun?',['Audio/video uzatish','Internet tarqatish','Fayl siqish','RAM oshirish'],0],
['Kompyuter','GPU nima bilan ko‘proq bog‘liq?',['Grafik hisoblash','Matn terish','Audio yozish','Printer'],0],
['Kompyuter','Motherboard nima?',['Asosiy plata','Monitor','Klaviatura','Operatsion tizim'],0],
['Kompyuter','BIOS/UEFI nima uchun?',['Kompyuter ishga tushish jarayonini boshlash va apparatni sozlash','Internet tezligini oshirish','Word ochish','Rasm tahrirlash'],0],
['Kompyuter','Fayl kengaytmasi .pdf odatda nima?',['Hujjat formati','Rasm formati faqat','Audio','Executable'],0],
['Kompyuter','.jpg nima?',['Rasm formati','Audio','Video','Arxiv'],0],
['Kompyuter','.mp3 nima?',['Audio','Rasm','Matn','Database'],0],
['Kompyuter','.zip nima?',['Arxiv','Video','OS','Drayver'],0],
['Kompyuter','Antivirus dasturining vazifasi?',['Zararli dasturlarni aniqlash va himoyalash','Internet yaratish','RAMni fizik oshirish','Monitorni ta’mirlash'],0],
['Kompyuter','Phishing nima?',['Soxta xabar/sayt orqali ma’lumotni qo‘lga kiritishga urinish','Kompyuter tozalash','Video montaj','Backup turi'],0],
['Kompyuter','Kuchli parolning foydasi?',['Hisob xavfsizligini oshiradi','Internetni tezlashtiradi','RAMni ko‘paytiradi','Ekranni yorqin qiladi'],0],
['Kompyuter','2FA nimani anglatadi?',['Ikki bosqichli autentifikatsiya','Ikki fayl arxivi','Ikki CPU','Ikki format'],0],
['Kompyuter','Cloud storage nima?',['Ma’lumotni internetdagi serverlarda saqlash','Faqat USB','RAM','Monitor'],0],
['Kompyuter','Backup nima?',['Zaxira nusxa','Virus','Brauzer','Driver'],0],
['Kompyuter','Driver nima?',['OS va qurilma o‘rtasida ishlashga yordam beruvchi dastur','Antivirus turi','Brauzer','Fayl arxivi'],0],
['Kompyuter','Printer nima qiladi?',['Hujjat/tasvirni qog‘ozga chiqaradi','Internet beradi','RAM saqlaydi','Video o‘ynaydi'],0],
['Kompyuter','Keyboard nima?',['Klaviatura','Sichqoncha','Monitor','Printer'],0],
['Kompyuter','Mouse nima?',['Sichqoncha','Klaviatura','CPU','SSD'],0],
['Kompyuter','Recycle Bin nima?',['O‘chirilgan fayllar vaqtincha saqlanadigan joy','Antivirus','RAM','Brauzer'],0],
['Kompyuter','Ctrl+Z odatda nima qiladi?',['Bekor qiladi','Saqlaydi','Nusxalaydi','Qidiradi'],0],
['Kompyuter','Ctrl+X nima qiladi?',['Kesadi','Nusxalaydi','Joylaydi','Saqlaydi'],0],
['Kompyuter','Alt+Tab nima uchun?',['Ochiq oynalar orasida almashish','Kompyuterni o‘chirish','Saqlash','Qidirish'],0],
['Kompyuter','Windows + D nima qiladi?',['Desktopni ko‘rsatadi/yashiradi','Fayl o‘chiradi','Task Manager ochadi','Restart qiladi'],0],
['Kompyuter','F5 brauzerda odatda nima qiladi?',['Sahifani yangilaydi','Saqlaydi','Yopadi','Qidiradi'],0],
['Kompyuter','Incognito/Private mode nimani anglatadi?',['Brauzerning lokal tarix kabi ma’lumotlarni odatdagidek saqlamaslik rejimi','To‘liq anonimlik kafolati','Antivirus','Internetni o‘chiradi'],0],
['Kompyuter','RAM hajmi odatda qaysi birlikda ko‘rsatiladi?',['GB','Hz','dpi','V'],0],
['Kompyuter','CPU tezligi ko‘pincha qaysi birlikda ko‘rsatiladi?',['GHz','GB','dpi','MB/s'],0],
['Kompyuter','Monitor yangilanish tezligi qaysi birlikda?',['Hz','GB','GHz','V'],0],
['Kompyuter','Screenshot nima?',['Ekran tasviri','Audio yozuv','Backup','Virus'],0],
['Kompyuter','Reboot nima?',['Qayta ishga tushirish','Fayl o‘chirish','Formatlash','Internet ulash'],0],
['Kompyuter','Formatlash odatda nimani anglatadi?',['Disk/bo‘limni ma’lum fayl tizimiga tayyorlash va mavjud ma’lumotlarni yo‘qotishi mumkin bo‘lgan amal','RAM oshirish','Monitor almashtirish','Brauzer yangilash'],0]
['Bootstrap','Bootstrapda d-none utilitysi nima qiladi?',['Elementni yashiradi','Elementni qalin qiladi','Elementni markazlaydi','Elementni fixed qiladi'],0]
];
